_commit: v1.12.1-6-gbf0c0a5
_src_path: /Users/crthomas/code/charlesthomas/homelab-template
additionalResources: ''
backups: false
helm: false
homepageDescription: Movie Finder
homepageEnabled: true
homepageGroup: Media
homepageIcon: radarr
homepageName: Radarr
ingClass: nginx-internal
ingCname: ''
ingExtraAnnotations: ''
ingHost: radarr.crt.house
ingName: radarr
ingPathType: Prefix
ingWebSockets: true
ingress: true
labels: ''
name: radarr
namespace: radarr
pvc: false
reloader: true
resources:
- deployments.yaml
- external-secrets.yaml
- ingresses.yaml
- pvcs.yaml
- service-accounts.yaml
- services.yaml
- statefulsets.yaml
service: false
serviceAccount: false
svcName: radarr
svcPortNum: 7878
upstreamURL: https://radarr.video/
url: https://github.com/charlesthomas/homelab-radarr
