---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: radarr
  namespace: radarr
  labels:
    app: radarr
spec:
  selector:
    matchLabels:
      app: radarr
  template:
    metadata:
      labels:
        app: radarr
    spec:
      dnsConfig:
        nameservers:
        - 10.43.0.10
      dnsPolicy: None
      initContainers:
      - name: cp-config
        image: alpine:latest
        resources: {}
        volumeMounts:
          - name: radarr-config
            mountPath: /tmp/radarr-config
          - name: radarr
            mountPath: /config
        command:
          - cp
          - -v
          - /tmp/radarr-config/config.xml
          - /config/config.xml
      containers:
      - name: radarr
        image: radarr
        imagePullPolicy: IfNotPresent
        ports:
        - name: radarr
          containerPort: 7878
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "America/Detroit"
        - name: UMASK
          value: "022"
        volumeMounts:
        - name: radarr
          mountPath: /config
        - name: media
          mountPath: /mnt/media
        resources: {}
        readinessProbe:
          tcpSocket:
            port: radarr
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: radarr
          initialDelaySeconds: 15
          periodSeconds: 20
      volumes:
      - name: radarr
        persistentVolumeClaim:
          claimName: radarr
      - name: radarr-config
        secret:
          secretName: radarr-config
      - name: media
        nfs:
          path: /volume1/media/
          server: 192.168.1.21

