---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: radarr-config
  namespace: radarr
spec:
  target:
    name: radarr-config
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        config.xml: |-
          {{ .config }}
  data:
    - secretKey: config
      sourceRef:
        storeRef:
          name: bitwarden-notes
          kind: ClusterSecretStore
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: radarr-config
        metadataPolicy: None
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres
  namespace: radarr
spec:
  target:
    name: postgres
    deletionPolicy: Delete
  data:
    - secretKey: password
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: 37d71b39-73fe-409c-bab2-0890e0892305
        metadataPolicy: None
        property: password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
    - secretKey: username
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: 37d71b39-73fe-409c-bab2-0890e0892305
        metadataPolicy: None
        property: username
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
